name: Build
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  cancel:
    runs-on: ubuntu-latest
    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.6.0
      with:
        access_token: ${{ github.token }}

  build:
    runs-on: ubuntu-latest
    needs: cancel
    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get install \
          clang-tools \
          libcmocka-dev \
          libhttp-parser-dev \
          libmbedtls-dev \
          lcov

    - name: Install jsmn
      run: |
        git clone https://github.com/zserge/jsmn.git
        make -C jsmn
        echo "CFLAGS=$CFLAGS -isystem $(pwd)/jsmn" >> $GITHUB_ENV
        echo "LDFLAGS=$LDFLAGS -L$(pwd)/jsmn" >> $GITHUB_ENV

    - name: Compile
      run: |
        mkdir build
        cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug -DENABLE_TESTING=ON -DCODE_COVERAGE=ON
        make -C build

    - name: Test
      run: |
        cd build
        make test ARGS="-V"
        make test_coverage

    - name: static analysis
      run: |
        mkdir build-csa
        scan-build cmake -S . -B build-csa -DCMAKE_BUILD_TYPE=Debug -DENABLE_TESTING=OFF -DCODE_COVERAGE=OFF
        scan-build --status-bugs make -C build-csa
